# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:15:16+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import RootModel


class Format(Enum):
    json = 'json'
    xml = 'xml'
    html = 'html'
    dump = 'dump'
    jpg = 'jpg'
    pdf = 'pdf'


class Ids(RootModel[List]):
    root: List


class Codes(RootModel[List]):
    root: List


class GraphId(RootModel[List]):
    root: List


class Color(RootModel[List]):
    root: List
